status handling added

diff --git a/templates/restic_script_Linux.j2 b/templates/restic_script_Linux.j2
--- a/templates/restic_script_Linux.j2
+++ b/templates/restic_script_Linux.j2
@@ -2,7 +2,6 @@
 # {{ ansible_managed }}
 # Backup script for {{ item.src|default('stdin') }}
 # Use this file to create a Backup and prune existing data with one execution.
-
 {% if item.disable_logging is defined and item.disable_logging %}
 {% set backup_result_log, backup_output_log = "/dev/null", "/dev/null" %}
 {% set forget_result_log, forget_output_log = "/dev/null", "/dev/null" %}
@@ -14,13 +13,14 @@
 {% set before_result_log, before_output_log = restic_log_dir + "/" + item.name + "-before-result.log", restic_log_dir + "/" + item.name + "-before-output.log" %}
 {% set after_result_log, after_output_log = restic_log_dir + "/" + item.name + "-after-result.log", restic_log_dir + "/" + item.name + "-after-output.log" %}
 {% endif %}
-
 {#
   Include access file
 #}
+# Include access file
 source {{ restic_script_dir }}/access-{{ item.name }}.sh
 
 set -uxo pipefail
+STATUS="NO_ERROR"
 {#
   Define Tags
 #}
@@ -48,14 +48,13 @@ set -uxo pipefail
 {#
   Define backup src list
 #}
-{% macro backup_src_list(item) -%}
+{% macro backup_src_list(item) %}
   {% if item.src is defined -%}
     {% for src_item in item.src -%}
         {{ src_item + " " }} 
     {%- endfor %}
   {% endif %}
 {% endmacro %}
-
 {#
   Define pathAttribute
 #}
@@ -68,7 +67,6 @@ set -uxo pipefail
     --path {{ repo.stdin_filename + " " }}
   {% endif %}
 {%- endmacro %}
-
 {#
   Define retention pattern
 #}
@@ -109,72 +107,81 @@ set -uxo pipefail
     {% endif %}
 {% endmacro %}
 
-
 {#
-  Define beforeScript execution
+  Define beforeScript execution 
 #}
-{% if item.before_script is defined %}
-  source {{ restic_script_dir }}/backup-{{ item.name }}-before.sh | tee {{ before_output_log }}
-  if [[ $? -eq 0 ]]
-  then
-      echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ before_result_log }}
-  else
-      echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ before_result_log }}
-  fi
+{% if item.before_script is defined -%}
+# before script
+source {{ restic_script_dir }}/backup-{{ item.name }}-before.sh | tee {{ before_output_log }}
+if [[ $? -eq 0 ]]
+then
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ before_result_log }}
+else
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ before_result_log }}
+    STATUS="beforeScript_failed"
+fi
 {% endif %}
-
-
 
 {#
   Define backup commands
 #}
-if [[ -z ${CRON+x} ]]; then
-  MODE_TAG="--tag manual"
-else
-  MODE_TAG="--tag cron"
-fi
+# backup command
+if [[ "$STATUS" = "NO_ERROR" ]]
+then  
+  if [[ -z ${CRON+x} ]]; then
+    MODE_TAG="--tag manual"
+  else
+    MODE_TAG="--tag cron"
+  fi
 
-{% if item.stdin is defined and item.stdin == true %}
-  {{ item.stdin_cmd }} | {{ restic_install_path }}/restic backup \
-    --stdin $MODE_TAG \
-    {{ tags(item.tags) }} \
-    {{ stdin_filename(item.stdin_filename) }} \
-    {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
-    $@ \
-{% else %}
-  {{ restic_install_path }}/restic backup {{ backup_src_list(item) }} $MODE_TAG \
-    {{ tags(item.tags) }} \
-    {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
-    $@ \
-{% endif %} | tee {{ backup_output_log }}
-if [[ $? -eq 0 ]]
-then
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ backup_result_log }}
-else
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ backup_result_log }}
+  {% if item.stdin is defined and item.stdin == true %}
+    {{ item.stdin_cmd }} | {{ restic_install_path }}/restic backup \
+      --stdin $MODE_TAG \
+      {{ tags(item.tags) }} \
+      {{ stdin_filename(item.stdin_filename) }} \
+      {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
+      $@ \
+  {% else %}
+    {{ restic_install_path }}/restic backup {{ backup_src_list(item) }} $MODE_TAG \
+      {{ tags(item.tags) }} \
+      {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
+      $@ \
+  {% endif %} | tee {{ backup_output_log }}
+  if [[ $? -eq 0 ]]
+  then
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ backup_result_log }}
+  else
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ backup_result_log }}
+      STATUS="backup_failed"
+  fi
 fi
 
 {#
   Define stdin forget commands
 #}
-{{ restic_install_path }}/restic forget {{ path_attribute(item) }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} | tee {{ forget_output_log }}
-if [[ $? -eq 0 ]]
+# forget command
+if [[ "$STATUS" = "NO_ERROR" ]]
 then
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ forget_result_log }}
-else
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ forget_result_log }}
+  {{ restic_install_path }}/restic forget {{ path_attribute(item) }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} | tee {{ forget_output_log }}
+  if [[ $? -eq 0 ]]
+  then
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ forget_result_log }}
+  else
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ forget_result_log }}
+      STATUS="forget_failed"
+  fi
 fi
-
 
 {#
   Define aftereScript execution
 #}
 {% if item.after_script is defined %}
-  source {{ restic_script_dir }}/backup-{{ item.name }}-after.sh | tee {{ after_output_log }}
-  if [[ $? -eq 0 ]]
-  then
-      echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ after_result_log }}
-  else
-      echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ after_result_log }}
-  fi
+# after script
+source {{ restic_script_dir }}/backup-{{ item.name }}-after.sh $STATUS | tee {{ after_output_log }}
+if [[ $? -eq 0 ]]
+then
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ after_result_log }}
+else
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ after_result_log }}
+fi
 {% endif %}
