Improved backup script by removing duplicate code

diff --git a/templates/restic_script_Linux.j2 b/templates/restic_script_Linux.j2
--- a/templates/restic_script_Linux.j2
+++ b/templates/restic_script_Linux.j2
@@ -3,6 +3,14 @@
 # Backup script for {{ item.src|default('stdin') }}
 # Use this file to create a Backup and prune existing data with one execution.
 
+{% if item.disable_logging is defined and item.disable_logging %}
+{% set backup_result_log, backup_output_log = "/dev/null", "/dev/null" %}
+{% set forget_result_log, forget_output_log = "/dev/null", "/dev/null" %}
+{% else %}
+{% set backup_result_log, backup_output_log = restic_log_dir + "/" + item.name + "-backup-result.log", restic_log_dir + "/" + item.name + "-backup-output.log" %}
+{% set forget_result_log, forget_output_log = restic_log_dir + "/" + item.name + "-forget-result.log", restic_log_dir + "/" + item.name + "-forget-output.log" %}
+{% endif %}
+
 export RESTIC_REPOSITORY={{ restic_repos[item.repo].location }}
 export RESTIC_PASSWORD='{{ restic_repos[item.repo].password | regex_replace('\'', '\'\\\'\'') }}'
 BACKUP_NAME={{ item.name }}
@@ -24,7 +32,7 @@ export B2_ACCOUNT_KEY={{ restic_repos[item.repo].b2_account_key }}
 {% if item.src is defined %}
 BACKUP_SOURCE={{ item.src }}
 {% endif %}
-set -euxo pipefail
+set -uxo pipefail
 {#
   Define Tags
 #}
@@ -103,54 +111,33 @@ else
   MODE_TAG="--tag cron"
 fi
 
-
-{% if item.enable_logging is defined and item.enable_logging %}
-if [[ $({% if item.stdin is defined and item.stdin == true %}
-  {{ item.stdin_cmd }} | {{ restic_install_path }}/restic backup \
-    --stdin $MODE_TAG \
-    {{ tags(item.tags) }} \
-    {{ stdin_filename(item.stdin_filename) }} \
-    {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
-    $@
-{% else %}
-  {{ restic_install_path }}/restic backup $BACKUP_SOURCE $MODE_TAG \
-    {{ tags(item.tags) }} \
-    {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
-    $@ \
-{% endif %} | tee {{ restic_log_dir }}/{{ item.name }}-backup-output.log) ]]
-then
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ restic_log_dir }}/{{ item.name }}-backup-result.log
-else
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ restic_log_dir }}/{{ item.name }}-backup-result.log
-fi
-{#
-  Define stdin forget commands
-#}
-if [[ $({{ restic_install_path }}/restic forget --path {{ path(item) }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} | tee {{ restic_log_dir }}/{{ item.name }}-forget-output.log) ]]
-then
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ restic_log_dir }}/{{ item.name }}-forget-result.log
-else
-    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ restic_log_dir }}/{{ item.name }}-forget-result.log
-fi
-
-{% else %}
-
 {% if item.stdin is defined and item.stdin == true %}
   {{ item.stdin_cmd }} | {{ restic_install_path }}/restic backup \
     --stdin $MODE_TAG \
     {{ tags(item.tags) }} \
     {{ stdin_filename(item.stdin_filename) }} \
     {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
-    $@
+    $@ \
 {% else %}
   {{ restic_install_path }}/restic backup $BACKUP_SOURCE $MODE_TAG \
     {{ tags(item.tags) }} \
     {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
-    $@
-{% endif %}
+    $@ \
+{% endif %} | tee {{ backup_output_log }}
+if [[ $? -eq 0 ]]
+then
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ backup_result_log }}
+else
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ backup_result_log }}
+fi
+
 {#
   Define stdin forget commands
 #}
-{{ restic_install_path }}/restic forget --path {{ path(item) }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %}
-
-{% endif %}
+{{ restic_install_path }}/restic forget --path {{ path(item) }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} | tee {{ forget_output_log }}
+if [[ $? -eq 0 ]]
+then
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ forget_result_log }}
+else
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ forget_result_log }}
+fi
