before and after script added

diff --git a/templates/restic_script_Linux.j2 b/templates/restic_script_Linux.j2
--- a/templates/restic_script_Linux.j2
+++ b/templates/restic_script_Linux.j2
@@ -6,9 +6,13 @@
 {% if item.disable_logging is defined and item.disable_logging %}
 {% set backup_result_log, backup_output_log = "/dev/null", "/dev/null" %}
 {% set forget_result_log, forget_output_log = "/dev/null", "/dev/null" %}
+{% set before_result_log, before_output_log = "/dev/null", "/dev/null" %}
+{% set after_result_log, after_output_log = "/dev/null", "/dev/null" %}
 {% else %}
 {% set backup_result_log, backup_output_log = restic_log_dir + "/" + item.name + "-backup-result.log", restic_log_dir + "/" + item.name + "-backup-output.log" %}
 {% set forget_result_log, forget_output_log = restic_log_dir + "/" + item.name + "-forget-result.log", restic_log_dir + "/" + item.name + "-forget-output.log" %}
+{% set before_result_log, before_output_log = restic_log_dir + "/" + item.name + "-before-result.log", restic_log_dir + "/" + item.name + "-before-output.log" %}
+{% set after_result_log, after_output_log = restic_log_dir + "/" + item.name + "-after-result.log", restic_log_dir + "/" + item.name + "-after-output.log" %}
 {% endif %}
 
 {#
@@ -104,6 +108,23 @@ set -uxo pipefail
         {% endfor %}
     {% endif %}
 {% endmacro %}
+
+
+{#
+  Define beforeScript execution
+#}
+{% if item.before_script is defined %}
+  source {{ restic_script_dir }}/backup-{{ item.name }}-before.sh | tee {{ before_output_log }}
+  if [[ $? -eq 0 ]]
+  then
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ before_result_log }}
+  else
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ before_result_log }}
+  fi
+{% endif %}
+
+
+
 {#
   Define backup commands
 #}
@@ -143,3 +164,17 @@ then
 else
     echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ forget_result_log }}
 fi
+
+
+{#
+  Define aftereScript execution
+#}
+{% if item.after_script is defined %}
+  source {{ restic_script_dir }}/backup-{{ item.name }}-after.sh | tee {{ after_output_log }}
+  if [[ $? -eq 0 ]]
+  then
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ after_result_log }}
+  else
+      echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ after_result_log }}
+  fi
+{% endif %}
